USE master;
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'WB_EXAMEN_FINAL')
BEGIN
    ALTER DATABASE WB_EXAMEN_FINAL SET SINGLE_USER WITH ROLLBACK IMMEDIATE; 
    DROP DATABASE WB_EXAMEN_FINAL;
END
GO

-- CREACIÓN DE LA BASE DE DATOS
CREATE DATABASE WB_EXAMEN_FINAL;
GO

USE WB_EXAMEN_FINAL;
GO


CREATE TABLE CL_PAISES (
    ID_PAIS INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_PAIS VARCHAR(50) NOT NULL,
    ID_REGION INT NOT NULL,
    CONSTRAINT fk_region_pais FOREIGN KEY (ID_REGION) REFERENCES CL_REGIONES(ID_REGION)
);
GO

CREATE TABLE CL_CARGOS (
    ID_CARGOS INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_CARGO VARCHAR(100) NOT NULL,
    SALARIO_MINIMO DECIMAL(10,2) NOT NULL,
    SALARIO_MAXIMO DECIMAL(10,2) NOT NULL
);
GO


CREATE TABLE CL_LOCALIDAD(
    ID_LOCALIDAD INT PRIMARY KEY IDENTITY(1,1),
    DIRECCION VARCHAR(150) NULL,      
    CODIGO_POSTAL INT NULL,          
    CIUDAD VARCHAR(100) NOT NULL,
    ESTADO_PROVINCIA VARCHAR(50) NULL,
    ID_PAIS INT NOT NULL,
    CONSTRAINT fk_pais_localidad FOREIGN KEY(ID_PAIS) REFERENCES CL_PAISES(ID_PAIS)
);
GO

CREATE TABLE CL_DEPARTAMENTOS(
    ID_DPTO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_DPTO VARCHAR(100) NOT NULL,
    ID_GERENTE INT NULL,              
    ID_LOCALIDAD INT NOT NULL,
    CONSTRAINT fk_localidad_dpto FOREIGN KEY(ID_LOCALIDAD) REFERENCES CL_LOCALIDAD(ID_LOCALIDAD)
);
GO

CREATE TABLE CL_EMPLEADOS(
    ID_EMPLEADO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NULL,        
    FECHA_INGRESO DATE NOT NULL,    
    SUELDO DECIMAL(10,2) NOT NULL,
    PCT_COMISION DECIMAL(5,2) NULL,   
    ID_DPTO INT NOT NULL,
    ID_CARGOS INT NOT NULL,
    ID_GERENTE INT NULL,              
    
    CONSTRAINT fk_gerente_dpto  FOREIGN KEY (ID_GERENTE) REFERENCES CL_EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT fk_dpto_empleado FOREIGN KEY(ID_DPTO) REFERENCES CL_DEPARTAMENTOS(ID_DPTO),
    CONSTRAINT fk_cargo_empleado FOREIGN KEY(ID_CARGOS) REFERENCES CL_CARGOS(ID_CARGOS),
    CONSTRAINT fk_gerente_empleado FOREIGN KEY (ID_GERENTE) REFERENCES CL_EMPLEADOS(ID_EMPLEADO)
);
GO

CREATE TABLE CL_REGIONES(
    ID_REGION INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_REGION VARCHAR(50) NOT NULL
);
GO

-- REGIONES
INSERT INTO CL_REGIONES (NOMBRE_REGION) VALUES ('America'), ('Europa');

-- PAISES
INSERT INTO CL_PAISES (NOMBRE_PAIS, ID_REGION) VALUES 
('Peru', 1), 
('España', 2), 
('UNITED STATES OF AMERICA', 1); 

-- LOCALIDADES
INSERT INTO CL_LOCALIDAD (CIUDAD, ID_PAIS) VALUES 
('Lima', 1), 
('Madrid', 2), 
('New York', 3); 

-- DEPARTAMENTOS
INSERT INTO CL_DEPARTAMENTOS (NOMBRE_DPTO, ID_LOCALIDAD) VALUES 
('IT', 1), 
('HR', 2), 
('FINANCE', 3); 

-- CARGOS
INSERT INTO CL_CARGOS (NOMBRE_CARGO, SALARIO_MINIMO, SALARIO_MAXIMO) VALUES 
('Desarrollador', 2000, 5000), 
('Contador', 2500, 6000), 
('Gerente General', 8000, 15000); 

--  EMPLEADOS
INSERT INTO CL_EMPLEADOS (NOMBRES, APELLIDOS, EMAIL, FECHA_INGRESO, SUELDO, ID_DPTO, ID_CARGOS, ID_GERENTE) 
VALUES 
('Carlos', 'Jefe', 'jefe@empresa.com', '2020-01-01', 10000, 3, 3, NULL); 

INSERT INTO CL_EMPLEADOS (NOMBRES, APELLIDOS, EMAIL, FECHA_INGRESO, SUELDO, ID_DPTO, ID_CARGOS, ID_GERENTE) 
VALUES 
('Wilber', 'Becerra', 'wilber@dev.com', '2024-01-01', 3500, 1, 1, 1),
('Angie', 'Garcia', 'angie@fin.com', '2023-05-15', 4500, 3, 2, 1),
('John', 'Doe', 'john@usa.com', '2022-08-20', 4800, 3, 2, 1);
GO


-- STORED PROCEDURE --
-- TODOS LOS REGISTROS --
CREATE PROCEDURE SP_VER_TODOS_LOS_REGISTROS
AS
BEGIN
      SET NOCOUNT ON;
      SELECT

      (SELECT COUNT(*) FROM CL_REGIONES) AS Total_Regiones,
      (SELECT COUNT(*) FROM CL_CARGOS) AS Total_Cargos,
      (SELECT COUNT(*) FROM CL_PAISES) AS Total_Paises,
      (SELECT COUNT(*) FROM CL_LOCALIDAD) AS Total_Localidades,
      (SELECT COUNT(*) FROM CL_DEPARTAMENTOS) AS Total_Departamentos,
      (SELECT COUNT(*) FROM CL_EMPLEADOS) AS Total_Empleados;
END;
GO

EXEC SP_VER_TODOS_LOS_REGISTROS;
GO

CREATE PROCEDURE SP_VER_EMPLEADOS_POR_DEPARTAMENTO
    @IdDepartamento INT
AS
BEGIN
    SELECT * FROM CL_EMPLEADOS
    WHERE ID_DPTO = @IdDepartamento;
END;
GO

EXEC SP_VER_EMPLEADOS_POR_DEPARTAMENTO ;
GO

